name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hace check out en el repositorio
      uses: actions/checkout@v3
      
    - name: Login en docker hub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_TOKEN}}
        
    - name: Configura Docker Buldx
      id: buildx
      uses: docker/setup-build-action@v1
    - name: CREAR Y SUBIR IMAGEN
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tag: ${{ secrets.DOCKER_USERNAME}}/sql-server:clase 
        
    - name: digest de la imagen
      run: echo ${{ steps.docker_build.outputs.digest }}
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
